#!/bin/bash

SERVER_IP=$1
PORT=$2
USER=$3
PASSWORD=$4
REMOTE_PATH=$5
LOCAL_BACKUP_DIR=$6

mkdir -p "$LOCAL_BACKUP_DIR"

sshpass -p "$PASSWORD" scp -r -P $PORT \
"$USER@$SERVER_IP:$REMOTE_PATH" "$LOCAL_BACKUP_DIR"
